sudo: False

language: python

os:
  - linux
  - osx

matrix:
  include:
    - python: 2.6
    - python: 2.7
    - python: 3.3
    - python: 3.4

install:
  # Install conda
  - [[ $TRAVIS_PYTHON_VERSION == "osx" ]] && os=MacOSX || os=Linux
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-${os}-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n castra python=$TRAVIS_PYTHON_VERSION pytest numpy pandas
  - source activate castra
  - pip install bloscpack

script:
  - py.test -x --doctest-modules --pyargs castra

notifications:
  email: false
